version: '3.8'

services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"                                                                           # This is what you'll use from host / Python / aiokafka
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1                                                                        # Unique broker ID
      KAFKA_PROCESS_ROLES: broker,controller                                                  # Broker (handles data), Controller (handles metadata)
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,PLAINTEXT_HOST://:29092           # 9092 → client traffic, 9093 → controller communication
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER                                             # Controllers communicate via this listener
      # 
      
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1                                               # Consumer offsets stored with replication = 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LOG_DIRS: /var/lib/kafka/data                                                     # By default logs were stored in /tmp/kafka-logs
    volumes:
      - ./data:/var/lib/kafka/data                                                        # Where logs are stored

  kafka-ui:
    # image: provectuslabs/kafka-ui:latest
    image: kafbat/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: TBT-Data                                 # Display name in UI
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092                   # Initial connection point (bootstrap)
      DYNAMIC_CONFIG_ENABLED: "true"                                  # Allows runtime config updates
      # KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181


volumes:
  kafka-data:
  