import datetime
from pydantic import BaseModel, Field

from enum import Enum
class SignalType(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    STRONG_BUY = "STRONG_BUY"
    STRONG_SELL = "STRONG_SELL"

class StrategySignal(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"

class Signal(BaseModel):
    symbol: str
    resolution: str
    open_time: datetime.datetime
    close_price:              float | None     = Field(default=None)
    signal_type:              SignalType       = Field(..., description="Type of signal generated (e.g., 'BUY', 'SELL', 'HOLD')")
    strategy_EMA_crossover:   StrategySignal   = Field(..., description="Signal generated by EMA crossover strategy (e.g., 'BUY', 'SELL', 'HOLD')")
    strategy_RSI_reversal:    StrategySignal   = Field(..., description="Signal generated by RSI reversal strategy (e.g., 'BUY', 'SELL', 'HOLD')")
    strategy_MACD_crossover:  StrategySignal   = Field(..., description="Signal generated by MACD crossover strategy (e.g., 'BUY', 'SELL', 'HOLD')")
    strategy_VWAP_confluence: StrategySignal   = Field(..., description="Signal generated by VWAP confluence strategy (e.g., 'BUY', 'SELL', 'HOLD')")
    weighted_score:           float            = Field(..., description="Weighted score based on the combined strategies")
    threshold:                float            = Field(..., description="Threshold value for signal generation")





# Final result is signal_type — this is the aggregated result with a weighted_score backing it. This is where strength belongs:
# weighted_score > 0.75   →  STRONG_BUY
# weighted_score > 0.50   →  BUY
# -0.50 to 0.50           →  HOLD
# weighted_score < -0.50  →  SELL
# weighted_score < -0.75  →  STRONG_SELL


"""
This ... is called as ellipsis, which means the field is mandatory and must be provided when creating an instance of the model.

| Syntax                              | Meaning                   |
| ----------------------------------- | ------------------------- |
| `field: str`                        | Required                  |
| `field: str = Field(...)`           | Required + metadata       |
| `field: str = "buy"`                | Optional, default `"buy"` |
| `field: Optional[str] = None`       | Optional, default `None`  |
| `field: str = Field(default="buy")` | Optional + metadata       |


"""